---
data_args:
  # Data training arguments
  dataset: wikivitals-telecom # the name of the dataset (used only to display infos)
  max_seq_length: 128 # maximum number of tokens
  overwrite_cache: True 
  pad_to_max_length: True # pad to maximum length if True else no padding
  path_base: './datasets/wikivitals_telecom/' # the path to the dataset
  train_file: wv4_depth3_raw_train.json
  validation_file: wv4_depth3_raw_val.json
  test_file: wv4_depth3_raw_test.json
  fill_label_value_strategy: ~ # the strategy to adopt if some labels are missing
  task_labels_col: 'label'  # the column (for CSV files) of field (for JSON files) for the labels
  task_inputs_col: 'token' # the column (for CSV files) of field (for JSON files) for the input text
  multilabel_classification: True
  other_args: 
    depth: 3 # 1, 2 or 3 for wikivitals 
  debug_mode: False # activates debug mode if True (selection of a subset of the dataset for debugging purpose)
  debug_split_sizes: 10 # used only if debug_mode is True, size of the subsets of train, validation, and test sets

model_args:
  # Model arguments
  name_or_path: 'bert-base-uncased' # bert model to use (one can also specify a path)  
  classification_head: 'with_word_attention' # value among 'base_sequence_classifier', 'with_word_attention'
  hidden_dropout_prob: 0.2 # dropout probability for the classification head
  freeze_bert: False # wether to freeze bert or not during training
  
training_args:
  # Trainer arguments
  do_eval: False
  do_predict: False
  evaluation_strategy: 'no' 
  per_device_train_batch_size: 32
  per_device_eval_batch_size: 32
  gradient_accumulation_steps: 1
  eval_accumulation_steps: 1
  learning_rate: 1.e-5 # don't forget the '.'
  weight_decay: 0.1
  num_train_epochs: 60
  lr_scheduler_type: constant
  warmup_steps: 500
  logging_steps: 50
  seed: 42
  label_names: ~ # defaults to 'labels'
  report_to: 'tensorboard'
  save_total_limit: 1 # limits the total amount of checkpoints. Deletes the older checkpoints in output_dir.
  save_strategy: 'no' # in ['no', 'steps', 'epoch'], don't forget the quotes if 'no'
  output_dir: ./outputs_downstream_tasks # TO REMOVE
